name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      # Generate the snake SVG using Platane/snk
      - uses: Platane/snk@v3
        with:
          github_user_name: zidanaetrna
          outputs: |
            output/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Avoid API rate limits
      # Upload the generated SVG as an artifact (optional, for debugging)
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: output/snake.svg
          if-no-files-found: error # Ensure the step fails if the file isn't found
      # Commit and push the generated SVG to the repository
      - run: git config --global user.name "github-actions[bot]"
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - run: git commit -m "Update snake animation"
      - run: git push
