name: Generate Snake
on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: zidanaetrna
          outputs: |
            output/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: output/snake.svg
      - run: git config --global user.name "github-actions[bot]"
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add .
      - run: git commit -m "Update snake animation"
      - run: git push
